services:
  mysql:
    image: mysql:8.4
    container_name: glops-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: glops
      MYSQL_USER: glops_user
      MYSQL_PASSWORD: glops_password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - glops_mysql_data:/var/lib/mysql

volumes:
  glops_mysql_data: