export enum PaymentStatus {
  INITIATED = 'INITIATED',
  PENDING_ACTION = 'PENDING_ACTION',
  PENDING_CONFIRMATION = 'PENDING_CONFIRMATION',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  UNKNOWN = 'UNKNOWN',
  REQUIRES_RECONCILIATION = 'REQUIRES_RECONCILIATION',
}
